services:
  builder:
    build: .
    tty: true
    stdin_open: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - nuveke-builder:/app

volumes:
  nuveke-builder:
    external: true
