name: release

on:
  push:
    tags: 
      - "*"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble build
      - uses: softprops/action-gh-release@v1
        with:
          files: nuveke
